language: cpp

compiler:
  - gcc

install:
  - sudo apt-add-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib g++-multilib

script: ./build.sh
